public class RequestedServiceViewModel
{
    public int samplePerServiceId { get; set; }
    public int sampleTypeId { get; set; }
    public int sampleNo { get; set; }
    public int sampleServiceId { get; set; }
    public int sampleDepartmentId { get; set; }
    public int collectionSiteId { get; set; }
    public int referalTypeId { get; set; }
    public string referredBy { get; set; }
    public string sampleRemarks { get; set; }
    public int labTechnician { get; set; }
    public int labSupervisor { get; set; }
    public int labDoctor { get; set; }
    public int sampleStatusId { get; set; }
    public int stageId { get; set; }
    public int sampleHistoNo { get; set; }
    public int sampleEncodedBy { get; set; }
    public DateTime sampleEncodedDate { get; set; }
    public int sampleLastChangedBy { get; set; }
    public DateTime sampleLastChangeDate { get; set; }
    public int samplePatientId { get; set; }
    public int sampleUlid { get; set; }
    public string clinicalRemarks { get; set; }
    public DateTime provisionalResultDate { get; set; }
    public int provisionalResultReleasedBy { get; set; }
    public int reportTypeId { get; set; }
    public string finalRemarks { get; set; }
    public bool printStatus { get; set; }
    public bool printLabelSatus { get; set; }
    public DateTime testDateTime { get; set; }
    public bool redoDiagSampleId { get; set; }
    public bool isRedone { get; set; }
    public string sampleLocation { get; set; }
    public int employeeTypePhase { get; set; }
    public bool sampleIsHistoFilled { get; set; }
    public string serviceName { get; set; }
    public string stageType { get; set; }
    public string stage { get; set; }
    public string statusType { get; set; }
    public string status { get; set; }
    public string statusColor { get; set; }
    public int histoSampleId { get; set; }
    public int histoHistoNo { get; set; }
    public int histoSampleNo { get; set; }
    public int histoServiceId { get; set; }
    public string requisitionType { get; set; }
    public string specimenType { get; set; }
    public string specimenSite { get; set; }
    public bool previousBiopsy { get; set; }
    public string sutureTag { get; set; }
    public string clinicalDetails { get; set; }
    public string operativeFindings { get; set; }
    public string provisionalDiagnosis { get; set; }
    public string investigationRequested { get; set; }
    public bool sampleGrossingPerformed { get; set; }
    public int sampleGrossingPerformedBy { get; set; }
    public DateTime sampleGrossingPerformedDate { get; set; }
    public bool tissueProcessingPerformed { get; set; }
    public int tissueProcessingPerformedBy { get; set; }
    public DateTime tissueProcessingPerformedDate { get; set; }
    public bool embeddingPerformed { get; set; }
    public int embeddingPerformedBy { get; set; }
    public DateTime embeddingPerformedDate { get; set; }
    public bool microtomyPerformed { get; set; }
    public int microtomyPerformedBy { get; set; }
    public DateTime microtomyPerformedDate { get; set; }
    public bool stainingPerformed { get; set; }
    public int stainingPerformedBy { get; set; }
    public DateTime stainingPerformedDate { get; set; }
    public int sampleDetailId { get; set; }
    public int sampleDetailSampleNo { get; set; }
    public bool sampleCollected { get; set; }
    public int collectedBy { get; set; }
    public DateTime collectedDate { get; set; }
    public bool sampleAcknowledged { get; set; }
    public int acknowledgedBy { get; set; }
    public DateTime acknowledgedDate { get; set; }
    public bool sampleDispatched { get; set; }
    public int dispatchedBy { get; set; }
    public DateTime dispatchDate { get; set; }
    public bool cancelled { get; set; }
    public int cancelledBy { get; set; }
    public string cancellationReason { get; set; }
    public string sampleDetailRemarks { get; set; }
    public bool active { get; set; }
    public int sampleDetailEncodedBy { get; set; }
    public string firstName { get; set; }
    public string lastName { get; set; }
    public int age { get; set; }
    public string gender { get; set; }
}
